### ISSUE TITLE
Z3 frontend crash on 4.8

### ISSUE THREAD

**Issue by j29scott** [zhoulaifu/xsat#4]
Hi, I have in the past been able to get xsat to build, but am currently running into an error on 'make test'

(1) Working on Benchmarks/div2.c.30.smt2
   Compiling ...
[Xsat] The Z3 fornt-end crashes.
Traceback (most recent call last):
  File "xsat_gen.py", line 494, in <module>
    symbolTable, foo_dot_c=gen(expr_z3)
NameError: name 'expr_z3' is not defined
make: *** [build/foo.c] Error 1
Traceback (most recent call last):

Is this possibly caused by using z3 4.8 instead of 4.5?

EDIT: 

'make test' is now passing when reverting back to 4.5.1.0

**Comment by zhoulaifu** [comment]
Yes, it is very likely due to the API mismatch with Z3, which is used as a front end to parse constraints.
